public class BoltRefundTypesWiseReportController {
     public Boolean BoltRefundTypeGrouping{get;set;}
     public Boolean statusTypGrouping{get;set;}

    public Integer InstClsdAplgyAPcount{get;set;}
    public Integer InstClsdAplgydelhiupCount{get;set;}
    public Integer InstClsdAplgydelhiPunjbCount{get;set;}
    public Integer InstClsdAplgydelhiMPCount{get;set;}
    public Integer InstClsdAplgyEastAssamCount{get;set;}
    public Integer InstClsdAplgyEastWBCount{get;set;}
    public Integer InstClsdAplgyGujaratCount{get;set;}
    public Integer InstClsdAplgyKNKLCount{get;set;}
    public Integer InstClsdAplgyTnNorthCount{get;set;}
    public Integer InstClsdAplgyTnSouthCount{get;set;}
    public Integer InstClsdAplgyRajasthanCount{get;set;}
    public Integer InstClsdAplgyMumGoaCount{get;set;}
    public Integer InstClsdAplgyROMCount{get;set;}
    public Integer InstClsdAplgyBlankCount{get;set;}
    public Integer closedApologyTotalCount{get;set;}
    
    public Integer InstRefundAPcount{get;set;}
    public Integer InstRefunddelhiupCount{get;set;}
    public Integer InstRefunddelhiPunjbCount{get;set;}
    public Integer InstRefunddelhiMPCount{get;set;}
    public Integer InstRefundEastAssamCount{get;set;}
    public Integer InstRefundEastWBCount{get;set;}
    public Integer InstRefundGujaratCount{get;set;}
    public Integer InstRefundKNKLCount{get;set;}
    public Integer InstRefundTnNorthCount{get;set;}
    public Integer InstRefundTnSouthCount{get;set;}
    public Integer InstRefundRajasthanCount{get;set;}
    public Integer InstRefundMumGoaCount{get;set;}
    public Integer InstRefundROMCount{get;set;}
    public Integer InstRefundBlankCount{get;set;}
    public Integer InstRefundTotalCount{get;set;}
    
    public Integer InstBOAcceptAPcount{get;set;}
    public Integer InstBOAcceptdelhiupCount{get;set;}
    public Integer InstBOAcceptdelhiPunjbCount{get;set;}
    public Integer InstBOAcceptdelhiMPCount{get;set;}
    public Integer InstBOAcceptEastAssamCount{get;set;}
    public Integer InstBOAcceptEastWBCount{get;set;}
    public Integer InstBOAcceptGujaratCount{get;set;}
    public Integer InstBOAcceptKNKLCount{get;set;}
    public Integer InstBOAcceptTnNorthCount{get;set;}
    public Integer InstBOAcceptTnSouthCount{get;set;}
    public Integer InstBOAcceptRajasthanCount{get;set;}
    public Integer InstBOAcceptMumGoaCount{get;set;}
    public Integer InstBOAcceptROMCount{get;set;}
    public Integer InstBOAcceptBlankCount{get;set;}
    public Integer InstBOAcceptTotalCount{get;set;}
    
    public Integer BOcontstRejectAPcount{get;set;}
    public Integer BOcontstRejectdelhiupCount{get;set;}
    public Integer BOcontstRejectdelhiPunjbCount{get;set;}
    public Integer BOcontstRejectdelhiMPCount{get;set;}
    public Integer BOcontstRejectEastAssamCount{get;set;}
    public Integer BOcontstRejectEastWBCount{get;set;}
    public Integer BOcontstRejectGujaratCount{get;set;}
    public Integer BOcontstRejectKNKLCount{get;set;}
    public Integer BOcontstRejectTnNorthCount{get;set;}
    public Integer BOcontstRejectTnSouthCount{get;set;}
    public Integer BOcontstRejectRajasthanCount{get;set;}
    public Integer BOcontstRejectMumGoaCount{get;set;}
    public Integer BOcontstRejectROMCount{get;set;}
    public Integer BOcontstRejectBlankCount{get;set;}
    public Integer BOcontstRejectTotalCount{get;set;}
    
    public Integer redBusDelghtAPcount{get;set;}
    public Integer redBusDelghtdelhiupCount{get;set;}
    public Integer redBusDelghtdelhiPunjbCount{get;set;}
    public Integer redBusDelghtdelhiMPCount{get;set;}
    public Integer redBusDelghtEastAssamCount{get;set;}
    public Integer redBusDelghtEastWBCount{get;set;}
    public Integer redBusDelghtGujaratCount{get;set;}
    public Integer redBusDelghtKNKLCount{get;set;}
    public Integer redBusDelghtTnNorthCount{get;set;}
    public Integer redBusDelghtTnSouthCount{get;set;}
    public Integer redBusDelghtRajasthanCount{get;set;}
    public Integer redBusDelghtMumGoaCount{get;set;}
    public Integer redBusDelghtROMCount{get;set;}
    public Integer redBusDelghtBlankCount{get;set;}
    public Integer redBusDelghtTotalCount{get;set;}
    
    public Integer OutliercaseAPcount{get;set;}
    public Integer OutliercasedelhiupCount{get;set;}
    public Integer OutliercasedelhiPunjbCount{get;set;}
    public Integer OutliercasedelhiMPCount{get;set;}
    public Integer OutliercaseEastAssamCount{get;set;}
    public Integer OutliercaseEastWBCount{get;set;}
    public Integer OutliercaseGujaratCount{get;set;}
    public Integer OutliercaseKNKLCount{get;set;}
    public Integer OutliercaseTnNorthCount{get;set;}
    public Integer OutliercaseTnSouthCount{get;set;}
    public Integer OutliercaseRajasthanCount{get;set;}
    public Integer OutliercaseMumGoaCount{get;set;}
    public Integer OutliercaseROMCount{get;set;}
    public Integer OutliercaseBlankCount{get;set;}
    public Integer OutliercaseTotalCount{get;set;}
    
    public Integer BOcontestAcceptAPcount{get;set;}
    public Integer BOcontestAcceptdelhiupCount{get;set;}
    public Integer BOcontestAcceptdelhiPunjbCount{get;set;}
    public Integer BOcontestAcceptdelhiMPCount{get;set;}
    public Integer BOcontestAcceptEastAssamCount{get;set;}
    public Integer BOcontestAcceptEastWBCount{get;set;}
    public Integer BOcontestAcceptGujaratCount{get;set;}
    public Integer BOcontestAcceptKNKLCount{get;set;}
    public Integer BOcontestAcceptTnNorthCount{get;set;}
    public Integer BOcontestAcceptTnSouthCount{get;set;}
    public Integer BOcontestAcceptRajasthanCount{get;set;}
    public Integer BOcontestAcceptMumGoaCount{get;set;}
    public Integer BOcontestAcceptROMCount{get;set;}
    public Integer BOcontestAcceptBlankCount{get;set;}
    public Integer BOcontestAcceptTotalCount{get;set;}
    
    public Integer BOcontestAPcount{get;set;}
    public Integer BOcontestdelhiupCount{get;set;}
    public Integer BOcontestdelhiPunjbCount{get;set;}
    public Integer BOcontestdelhiMPCount{get;set;}
    public Integer BOcontestEastAssamCount{get;set;}
    public Integer BOcontestEastWBCount{get;set;}
    public Integer BOcontestGujaratCount{get;set;}
    public Integer BOcontestKNKLCount{get;set;}
    public Integer BOcontestTnNorthCount{get;set;}
    public Integer BOcontestTnSouthCount{get;set;}
    public Integer BOcontestRajasthanCount{get;set;}
    public Integer BOcontestMumGoaCount{get;set;}
    public Integer BOcontestROMCount{get;set;}
    public Integer BOcontestBlankCount{get;set;}
    public Integer BOcontestTotalCount{get;set;}
    
    public Integer TotalAPcount{get;set;}
    public Integer TotaldelhiupCount{get;set;}
    public Integer TotaldelhiPunjbCount{get;set;}
    public Integer TotaldelhiMPCount{get;set;}
    public Integer TotalEastAssamCount{get;set;}
    public Integer TotalEastWBCount{get;set;}
    public Integer TotalGujaratCount{get;set;}
    public Integer TotalKNKLCount{get;set;}
    public Integer TotalTnNorthCount{get;set;}
    public Integer TotalTnSouthCount{get;set;}
    public Integer TotalRajasthanCount{get;set;}
    public Integer TotalMumGoaCount{get;set;}
    public Integer TotalROMCount{get;set;}
    public Integer TotalBlankCount{get;set;}
    
    
    
    public Integer TotalCount{get;set;}
   
    public Integer statusTotalCount{get;set;}
    public Integer openAPcount{get;set;}
    public Integer opendelhiupCount{get;set;}
    public Integer openEastAssamCount{get;set;}
    public Integer openGujaratCount{get;set;}
    public Integer openKNKLCount{get;set;}
    public Integer opendelhiMPCount{get;set;}
    public Integer openTnNorthCount{get;set;}
    public Integer openMumGoaCount{get;set;}
    public Integer openBlankCount{get;set;}
    public Integer openStatusTotalCount{get;set;}

    public Integer EsclToBdAPcount{get;set;}
    public Integer EsclToBddelhiupCount{get;set;}
    public Integer EsclToBdEastAssamCount{get;set;}
    public Integer EsclToBdGujaratCount{get;set;}
    public Integer EsclToBdKNKLCount{get;set;}
    public Integer EsclToBdMPCount{get;set;}
    public Integer EsclToBdTnNorthCount{get;set;}
    public Integer EsclToBdMumGoaCount{get;set;}
    public Integer EsclToBdBlankCount{get;set;}
    public Integer EsclToBdTotalCount{get;set;}
    
    public Integer reopenAPcount{get;set;}
    public Integer reopendelhiupCount{get;set;}
    public Integer reopenEastAssamCount{get;set;}
    public Integer reopenGujaratCount{get;set;}
    public Integer reopenKNKLCount{get;set;}
    public Integer reopenMPCount{get;set;}
    public Integer reopenTnNorthCount{get;set;}
    public Integer reopenMumGoaCount{get;set;}
    public Integer reopenBlankCount{get;set;}
    public Integer reopenTotalCount{get;set;}
    
    public Integer BoRepliedAPcount{get;set;}
    public Integer BoReplieddelhiupCount{get;set;}
    public Integer BoRepliedEastAssamCount{get;set;}
    public Integer BoRepliedGujaratCount{get;set;}
    public Integer BoRepliedKNKLCount{get;set;}
    public Integer BoRepliedMPCount{get;set;}
    public Integer BoRepliedTnNorthCount{get;set;}
    public Integer BoRepliedMumGoaCount{get;set;}
    public Integer BoRepliedBlankCount{get;set;}
    public Integer BoRepliedTotalCount{get;set;}
    
    public Integer DepRevertAPcount{get;set;}
    public Integer DepRevertdelhiupCount{get;set;}
    public Integer DepRevertEastAssamCount{get;set;}
    public Integer DepRevertGujaratCount{get;set;}
    public Integer DepRevertKNKLCount{get;set;}
    public Integer DepRevertMPCount{get;set;}
    public Integer DepRevertTnNorthCount{get;set;}
    public Integer DepRevertMumGoaCount{get;set;}
    public Integer DepRevertBlankCount{get;set;}
    public Integer DepRevertTotalCount{get;set;}


    public Integer AwatngBoBdRespAPcount{get;set;}
    public Integer AwatngBoBdRespdelhiupCount{get;set;}
    public Integer AwatngBoBdRespEastAssamCount{get;set;}
    public Integer AwatngBoBdRespGujaratCount{get;set;}
    public Integer AwatngBoBdRespKNKLCount{get;set;}
    public Integer AwatngBoBdRespMPCount{get;set;}
    public Integer AwatngBoBdRespTnNorthCount{get;set;}
    public Integer AwatngBoBdRespMumGoaCount{get;set;}
    public Integer AwatngBoBdRespBlankCount{get;set;}
    public Integer AwatngBoBdRespTotalCount{get;set;}
 
    public Integer WatngforCustmrAPcount{get;set;}
    public Integer WatngforCustmrdelhiupCount{get;set;}
    public Integer WatngforCustmrEastAssamCount{get;set;}
    public Integer WatngforCustmrGujaratCount{get;set;}
    public Integer WatngforCustmrKNKLCount{get;set;}
    public Integer WatngforCustmrMPCount{get;set;}
    public Integer WatngforCustmrTnNorthCount{get;set;}
    public Integer WatngforCustmrMumGoaCount{get;set;}
    public Integer WatngforCustmrBlankCount{get;set;}
    public Integer WatngforCustmrTotalCount{get;set;}

  
    
 public list<RefundTypeWrapper> getRefundTypeGroup(){
        List<RefundTypeWrapper> finalMapList = New List<RefundTypeWrapper>();
        string strQuery = System.Label.BoltClosedCasesQuery;
        List<case> TotalCaseList  = Database.query(strQuery);
        TotalCount =0;
        if(!TotalCaseList.isEmpty()){
            TotalCount = Integer.valueOf(TotalCaseList.size());
              //Instant Closed with an Apology
            List<case>  InstClsdAplgylist = Database.query(strQuery +' AND Refund_Type__c=\'Instant Closed with an Apology\'');
        InstClsdAplgyAPcount=0;InstClsdAplgydelhiupCount=0;InstClsdAplgydelhiMPCount=0;InstClsdAplgydelhiPunjbCount=0;InstClsdAplgyEastAssamCount=0;InstClsdAplgyEastWBCount=0;InstClsdAplgyGujaratCount=0;InstClsdAplgyKNKLCount=0;InstClsdAplgyTnNorthCount=0;InstClsdAplgyTnSouthCount=0;InstClsdAplgyRajasthanCount=0;InstClsdAplgyMumGoaCount=0;InstClsdAplgyROMCount=0;InstClsdAplgyBlankCount=0;closedApologyTotalCount=0;
            if(!InstClsdAplgylist.isEmpty()){
                closedApologyTotalCount = Integer.valueOf(InstClsdAplgylist.size());
                for(case c : InstClsdAplgylist){
                     if(c.BD_Location__c == 'Andhra Pradesh' || c.BD_Location__c =='Telangana'){
                        InstClsdAplgyAPcount =InstClsdAplgyAPcount + 1;
                   }else if(c.BD_Location__c == 'Delhi + UP' || c.BD_Location__c == 'Delhi+Punjab'){
                        InstClsdAplgydelhiupCount =InstClsdAplgydelhiupCount + 1;
                   }else if(c.BD_Location__c == 'East (Assam)' || c.BD_Location__c == 'East (WB)'){
                        InstClsdAplgyEastAssamCount =InstClsdAplgyEastAssamCount + 1;
                   }else if(c.BD_Location__c == 'Gujarat'|| c.BD_Location__c == 'Rajasthan'){
                        InstClsdAplgyGujaratCount =InstClsdAplgyGujaratCount + 1;
                   }else if(c.BD_Location__c == 'KN + KL' || c.BD_Location__c=='Banglore'){
                        InstClsdAplgyKNKLCount =InstClsdAplgyKNKLCount + 1;
                   }else if(c.BD_Location__c == 'TN (North)'|| c.BD_Location__c == 'TN (South)' || c.BD_Location__c == 'Tamil Nadu'){
                        InstClsdAplgyTnNorthCount =InstClsdAplgyTnNorthCount + 1;
                   }else if(c.BD_Location__c == 'Mum + Goa' || c.BD_Location__c == 'ROM'){
                        InstClsdAplgyMumGoaCount =InstClsdAplgyMumGoaCount + 1;
                   }else if(c.BD_Location__c == 'Madhya Pradesh'){
                        InstClsdAplgydelhiMPCount =InstClsdAplgydelhiMPCount + 1;
                   }else {
                        InstClsdAplgyBlankCount =InstClsdAplgyBlankCount + 1;
                   }
                }
            }
            RefundTypeWrapper  InstClsdAplgyWrapper = New RefundTypeWrapper('Instant Closed with an Apology',InstClsdAplgyAPcount,InstClsdAplgydelhiupCount,InstClsdAplgyEastAssamCount,InstClsdAplgyGujaratCount,InstClsdAplgyKNKLCount,InstClsdAplgydelhiMPCount,InstClsdAplgyTnNorthCount,InstClsdAplgyMumGoaCount,InstClsdAplgyBlankCount,closedApologyTotalCount,((Decimal.valueOf(closedApologyTotalCount)/Decimal.valueOf(TotalCount))*100).setScale(0));
            finalMapList.add(InstClsdAplgyWrapper);
            
            //Instant resolution with refund
             List<case> InstRefundList = Database.query(strQuery +' AND Refund_Type__c=\'Instant resolution with refund\'');
        InstRefundAPcount=0;InstRefunddelhiupCount=0;InstRefunddelhiMPCount=0;InstRefunddelhiPunjbCount=0;InstRefundEastAssamCount=0;InstRefundEastWBCount=0;InstRefundGujaratCount=0;InstRefundKNKLCount=0;InstRefundTnNorthCount=0;InstRefundTnSouthCount=0;InstRefundRajasthanCount=0;InstRefundMumGoaCount=0;InstRefundROMCount=0;InstRefundBlankCount=0;InstRefundTotalCount=0;
            if(!InstRefundList.isEmpty()){
                InstRefundTotalCount = Integer.valueOf(InstRefundList.size());
                for(case c : InstRefundList){
                     if(c.BD_Location__c == 'Andhra Pradesh' || c.BD_Location__c =='Telangana'){
                        InstRefundAPcount =InstRefundAPcount + 1;
                   }else if(c.BD_Location__c == 'Delhi + UP' || c.BD_Location__c == 'Delhi+Punjab'){
                        InstRefunddelhiupCount =InstRefunddelhiupCount + 1;
                   }else if(c.BD_Location__c == 'East (Assam)' || c.BD_Location__c == 'East (WB)'){
                        InstRefundEastAssamCount =InstRefundEastAssamCount + 1;
                   }else if(c.BD_Location__c == 'Gujarat' || c.BD_Location__c == 'Rajasthan'){
                        InstRefundGujaratCount =InstRefundGujaratCount + 1;
                   }else if(c.BD_Location__c == 'KN + KL' || c.BD_Location__c=='Banglore'){
                        InstRefundKNKLCount =InstRefundKNKLCount + 1;
                   }else if(c.BD_Location__c == 'Madhya Pradesh'){
                        InstRefunddelhiMPCount =InstRefunddelhiMPCount + 1;
                   }else if(c.BD_Location__c == 'TN (North)' || c.BD_Location__c == 'TN (South)'){
                        InstRefundTnNorthCount =InstRefundTnNorthCount + 1;
                   }else if(c.BD_Location__c == 'Mum + Goa' || c.BD_Location__c == 'ROM'){
                        InstRefundMumGoaCount =InstRefundMumGoaCount + 1;
                   }else {
                        InstRefundBlankCount =InstRefundBlankCount + 1;
                   }
                }
            }
            RefundTypeWrapper InstRefundListWrapper = New RefundTypeWrapper('Instant resolution with refund',InstRefundAPcount,InstRefunddelhiupCount,InstRefundEastAssamCount,InstRefundGujaratCount,InstRefundKNKLCount,InstRefunddelhiMPCount,InstRefundTnNorthCount,InstRefundMumGoaCount,InstRefundBlankCount,InstRefundTotalCount,((Decimal.valueOf(InstRefundTotalCount)/Decimal.valueOf(TotalCount))*100).setScale(0));
            finalMapList.add(InstRefundListWrapper);
            
             //Instant resolution - BO Accepted 
            List<case>  InstBOAcceptList = Database.query(strQuery +' AND Refund_Type__c=\'Instant resolution - BO Accepted\'');
           InstBOAcceptAPcount=0;InstBOAcceptdelhiupCount=0;InstBOAcceptdelhiMPCount=0;InstBOAcceptdelhiPunjbCount=0;InstBOAcceptEastAssamCount=0;InstBOAcceptEastWBCount=0;InstBOAcceptGujaratCount=0;InstBOAcceptKNKLCount=0;InstBOAcceptTnNorthCount=0;InstBOAcceptTnSouthCount=0;InstBOAcceptRajasthanCount=0;InstBOAcceptMumGoaCount=0;InstBOAcceptROMCount=0;InstBOAcceptBlankCount=0;InstBOAcceptTotalCount=0;
            if(!InstBOAcceptList.isEmpty()){
                InstBOAcceptTotalCount = Integer.valueOf(InstBOAcceptList.size());
                for(case c : InstBOAcceptList){
                     if(c.BD_Location__c == 'Andhra Pradesh' || c.BD_Location__c =='Telangana'){
                        InstBOAcceptAPcount =InstBOAcceptAPcount + 1;
                   }else if(c.BD_Location__c == 'Delhi + UP' || c.BD_Location__c == 'Delhi+Punjab'){
                        InstBOAcceptdelhiupCount =InstBOAcceptdelhiupCount + 1;
                   }else if(c.BD_Location__c == 'East (Assam)' || c.BD_Location__c == 'East (WB)'){
                        InstBOAcceptEastAssamCount =InstBOAcceptEastAssamCount + 1;
                   }else if(c.BD_Location__c == 'Gujarat' || c.BD_Location__c == 'Rajasthan'){
                        InstBOAcceptGujaratCount =InstBOAcceptGujaratCount + 1;
                   }else if(c.BD_Location__c == 'KN + KL' || c.BD_Location__c=='Banglore'){
                        InstBOAcceptKNKLCount =InstBOAcceptKNKLCount + 1;
                   }else if(c.BD_Location__c == 'Madhya Pradesh'){
                        InstBOAcceptdelhiMPCount =InstBOAcceptdelhiMPCount + 1;
                   }else if(c.BD_Location__c == 'TN (North)' || c.BD_Location__c == 'TN (South)'){
                        InstBOAcceptTnNorthCount =InstBOAcceptTnNorthCount + 1;
                   }else if(c.BD_Location__c == 'Mum + Goa' || c.BD_Location__c == 'ROM'){
                        InstBOAcceptMumGoaCount =InstBOAcceptMumGoaCount + 1;
                   }else {
                        InstBOAcceptBlankCount =InstBOAcceptBlankCount + 1;
                   }
                }
            }
            RefundTypeWrapper InstBOAcceptListWrapper = New RefundTypeWrapper('Instant resolution - BO Accepted',InstBOAcceptAPcount,InstBOAcceptdelhiupCount,InstBOAcceptEastAssamCount,InstBOAcceptGujaratCount,InstBOAcceptKNKLCount,InstBOAcceptdelhiMPCount,InstBOAcceptTnNorthCount,InstBOAcceptMumGoaCount,InstBOAcceptBlankCount,InstBOAcceptTotalCount,((Decimal.valueOf(InstBOAcceptTotalCount)/Decimal.valueOf(TotalCount))*100).setScale(0));
            finalMapList.add(InstBOAcceptListWrapper);
            
          //Instant resolution - BO contest Rejected 
          List<case> BOcontstRejectList = Database.query(strQuery +' AND Refund_Type__c=\'Instant resolution - BO contest Rejected\'');
            BOcontstRejectAPcount=0;BOcontstRejectdelhiupCount=0;BOcontstRejectdelhiMPCount=0;BOcontstRejectdelhiPunjbCount=0;BOcontstRejectEastAssamCount=0;BOcontstRejectEastWBCount=0;BOcontstRejectGujaratCount=0;BOcontstRejectKNKLCount=0;BOcontstRejectTnNorthCount=0;BOcontstRejectTnSouthCount=0;BOcontstRejectRajasthanCount=0;BOcontstRejectMumGoaCount=0;BOcontstRejectROMCount=0;BOcontstRejectBlankCount=0;BOcontstRejectTotalCount=0;
            if(!BOcontstRejectList.isEmpty()){
                BOcontstRejectTotalCount = Integer.valueOf(BOcontstRejectList.size());
                for(case c : BOcontstRejectList){
                     if(c.BD_Location__c == 'Andhra Pradesh' || c.BD_Location__c =='Telangana'){
                        BOcontstRejectAPcount =BOcontstRejectAPcount + 1;
                   }else if(c.BD_Location__c == 'Delhi + UP' || c.BD_Location__c == 'Delhi+Punjab'){
                        BOcontstRejectdelhiupCount =BOcontstRejectdelhiupCount + 1;
                   }else if(c.BD_Location__c == 'East (Assam)' || c.BD_Location__c == 'East (WB)'){
                        BOcontstRejectEastAssamCount =BOcontstRejectEastAssamCount + 1;
                   }else if(c.BD_Location__c == 'Gujarat' || c.BD_Location__c == 'Rajasthan'){
                        BOcontstRejectGujaratCount =BOcontstRejectGujaratCount + 1;
                   }else if(c.BD_Location__c == 'KN + KL' || c.BD_Location__c=='Banglore'){
                        BOcontstRejectKNKLCount =BOcontstRejectKNKLCount + 1;
                   }else if(c.BD_Location__c == 'Madhya Pradesh'){
                        BOcontstRejectdelhiMPCount =BOcontstRejectdelhiMPCount + 1;
                   }else if(c.BD_Location__c == 'TN (North)'|| c.BD_Location__c == 'TN (South)'){
                        BOcontstRejectTnNorthCount =BOcontstRejectTnNorthCount + 1;
                   }else if(c.BD_Location__c == 'Mum + Goa' || c.BD_Location__c == 'ROM'){
                        BOcontstRejectMumGoaCount =BOcontstRejectMumGoaCount + 1;
                   }else {
                        BOcontstRejectBlankCount =BOcontstRejectBlankCount + 1;
                   }
                }
            }
            RefundTypeWrapper BOcontstRejectListWrapper = New RefundTypeWrapper('Instant resolution - BO contest Rejected',BOcontstRejectAPcount,BOcontstRejectdelhiupCount,BOcontstRejectEastAssamCount,BOcontstRejectGujaratCount,BOcontstRejectKNKLCount,BOcontstRejectdelhiMPCount,BOcontstRejectTnNorthCount,BOcontstRejectMumGoaCount,BOcontstRejectBlankCount,BOcontstRejectTotalCount,((Decimal.valueOf(BOcontstRejectTotalCount)/Decimal.valueOf(TotalCount))*100).setScale(0));
            finalMapList.add(BOcontstRejectListWrapper);
            
            //Instant resolution - RedBus Delight
        List<case>  redBusDelghtList = Database.query(strQuery +' AND Refund_Type__c=\'Instant resolution - redBus Delight\'');
           redBusDelghtAPcount=0;redBusDelghtdelhiupCount=0;redBusDelghtdelhiMPCount=0;redBusDelghtdelhiPunjbCount=0;redBusDelghtEastAssamCount=0;redBusDelghtEastWBCount=0;redBusDelghtGujaratCount=0;redBusDelghtKNKLCount=0;redBusDelghtTnNorthCount=0;redBusDelghtTnSouthCount=0;redBusDelghtRajasthanCount=0;redBusDelghtMumGoaCount=0;redBusDelghtROMCount=0;redBusDelghtBlankCount=0;redBusDelghtTotalCount=0;
            if(!redBusDelghtList.isEmpty()){
                redBusDelghtTotalCount = Integer.valueOf(redBusDelghtList.size());
                for(case c : redBusDelghtList){
                     if(c.BD_Location__c == 'Andhra Pradesh'|| c.BD_Location__c =='Telangana'){
                        redBusDelghtAPcount =redBusDelghtAPcount + 1;
                   }else if(c.BD_Location__c == 'Delhi + UP' || c.BD_Location__c == 'Delhi+Punjab'){
                        redBusDelghtdelhiupCount =redBusDelghtdelhiupCount + 1;
                   }else if(c.BD_Location__c == 'East (Assam)' || c.BD_Location__c == 'East (WB)'){
                        redBusDelghtEastAssamCount =redBusDelghtEastAssamCount + 1;
                   }else if(c.BD_Location__c == 'Gujarat' || c.BD_Location__c == 'Rajasthan'){
                        redBusDelghtGujaratCount =redBusDelghtGujaratCount + 1;
                   }else if(c.BD_Location__c == 'KN + KL' || c.BD_Location__c=='Banglore'){
                        redBusDelghtKNKLCount =redBusDelghtKNKLCount + 1;
                   }else if(c.BD_Location__c == 'Madhya Pradesh'){
                        redBusDelghtdelhiMPCount =redBusDelghtdelhiMPCount + 1;
                   }else if(c.BD_Location__c == 'TN (North)' || c.BD_Location__c == 'TN (South)'){
                        redBusDelghtTnNorthCount =redBusDelghtTnNorthCount + 1;
                   }else if(c.BD_Location__c == 'Mum + Goa' || c.BD_Location__c == 'ROM'){
                        redBusDelghtMumGoaCount =redBusDelghtMumGoaCount + 1;
                   }else {
                        redBusDelghtBlankCount =redBusDelghtBlankCount + 1;
                   }
                }
            }
            RefundTypeWrapper redBusDelghtListWrapper = New RefundTypeWrapper('Instant resolution - redBus Delight',redBusDelghtAPcount,redBusDelghtdelhiupCount,redBusDelghtEastAssamCount,redBusDelghtGujaratCount,redBusDelghtKNKLCount,redBusDelghtdelhiMPCount,redBusDelghtTnNorthCount,redBusDelghtMumGoaCount,redBusDelghtBlankCount,redBusDelghtTotalCount,((Decimal.valueOf(redBusDelghtTotalCount)/Decimal.valueOf(TotalCount))*100).setScale(0));
            finalMapList.add(redBusDelghtListWrapper);
            
            //OutLierCase
          List<case>   OutliercaseList = Database.query(strQuery +' AND Refund_Type__c=\'Outlier case\'');
            OutliercaseAPcount=0; OutliercasedelhiupCount=0;OutliercasedelhiMPCount=0;OutliercasedelhiPunjbCount=0; OutliercaseEastAssamCount=0; OutliercaseEastWBCount=0; OutliercaseGujaratCount=0; OutliercaseKNKLCount=0; OutliercaseTnNorthCount=0; OutliercaseTnSouthCount=0; OutliercaseRajasthanCount=0; OutliercaseMumGoaCount=0; OutliercaseROMCount=0; OutliercaseBlankCount=0; OutliercaseTotalCount=0;
            if(! OutliercaseList.isEmpty()){
                 OutliercaseTotalCount = Integer.valueOf( OutliercaseList.size());
                for(case c :  OutliercaseList){
                     if(c.BD_Location__c == 'Andhra Pradesh' || c.BD_Location__c =='Telangana'){
                         OutliercaseAPcount = OutliercaseAPcount + 1;
                   }else if(c.BD_Location__c == 'Delhi + UP' || c.BD_Location__c == 'Delhi+Punjab'){
                         OutliercasedelhiupCount = OutliercasedelhiupCount + 1;
                   }else if(c.BD_Location__c == 'East (Assam)' || c.BD_Location__c == 'East (WB)'){
                         OutliercaseEastAssamCount = OutliercaseEastAssamCount + 1;
                   }else if(c.BD_Location__c == 'Gujarat' || c.BD_Location__c == 'Rajasthan'){
                         OutliercaseGujaratCount = OutliercaseGujaratCount + 1;
                   }else if(c.BD_Location__c == 'KN + KL' || c.BD_Location__c=='Banglore'){
                         OutliercaseKNKLCount = OutliercaseKNKLCount + 1;
                   }else if(c.BD_Location__c == 'Madhya Pradesh'){
                         OutliercasedelhiMPCount = OutliercasedelhiMPCount + 1;
                   }else if(c.BD_Location__c == 'TN (North)' || c.BD_Location__c == 'TN (South)'){
                         OutliercaseTnNorthCount = OutliercaseTnNorthCount + 1;
                   }else if(c.BD_Location__c == 'Mum + Goa' || c.BD_Location__c == 'ROM'){
                         OutliercaseMumGoaCount = OutliercaseMumGoaCount + 1;
                   }else {
                         OutliercaseBlankCount = OutliercaseBlankCount + 1;
                   }
                }
            }
            RefundTypeWrapper  OutliercaseListWrapper = New RefundTypeWrapper('Outlier case', OutliercaseAPcount, OutliercasedelhiupCount, OutliercaseEastAssamCount, OutliercaseGujaratCount, OutliercaseKNKLCount, OutliercasedelhiMPCount, OutliercaseTnNorthCount, OutliercaseMumGoaCount, OutliercaseBlankCount, OutliercaseTotalCount,((Decimal.valueOf( OutliercaseTotalCount)/Decimal.valueOf(TotalCount))*100).setScale(0));
            finalMapList.add( OutliercaseListWrapper);
            
             // Instant resolution - BO contest Accepted
            List<case>   BOcontestAcceptList = Database.query(strQuery +' AND Refund_Type__c=\'Instant resolution - BO contest Accepted\'');
            BOcontestAcceptAPcount=0; BOcontestAcceptdelhiupCount=0;BOcontestAcceptdelhiMPCount=0;BOcontestAcceptdelhiPunjbCount=0; BOcontestAcceptEastAssamCount=0; BOcontestAcceptEastWBCount=0; BOcontestAcceptGujaratCount=0; BOcontestAcceptKNKLCount=0; BOcontestAcceptTnNorthCount=0; BOcontestAcceptTnSouthCount=0; BOcontestAcceptRajasthanCount=0; BOcontestAcceptMumGoaCount=0; BOcontestAcceptROMCount=0; BOcontestAcceptBlankCount=0; BOcontestAcceptTotalCount=0;
            if(! BOcontestAcceptList.isEmpty()){
                 BOcontestAcceptTotalCount = Integer.valueOf( BOcontestAcceptList.size());
                for(case c :  BOcontestAcceptList){
                     if(c.BD_Location__c == 'Andhra Pradesh' || c.BD_Location__c =='Telangana'){
                         BOcontestAcceptAPcount = BOcontestAcceptAPcount + 1;
                   }else if(c.BD_Location__c == 'Delhi + UP' || c.BD_Location__c == 'Delhi+Punjab'){
                         BOcontestAcceptdelhiupCount = BOcontestAcceptdelhiupCount + 1;
                   }else if(c.BD_Location__c == 'East (Assam)' || c.BD_Location__c == 'East (WB)'){
                         BOcontestAcceptEastAssamCount = BOcontestAcceptEastAssamCount + 1;
                   }else if(c.BD_Location__c == 'Gujarat' || c.BD_Location__c == 'Rajasthan'){
                         BOcontestAcceptGujaratCount = BOcontestAcceptGujaratCount + 1;
                   }else if(c.BD_Location__c == 'KN + KL' || c.BD_Location__c=='Banglore'){
                         BOcontestAcceptKNKLCount = BOcontestAcceptKNKLCount + 1;
                   }else if(c.BD_Location__c == 'Madhya Pradesh'){
                         BOcontestAcceptdelhiMPCount = BOcontestAcceptdelhiMPCount + 1;
                   }else if(c.BD_Location__c == 'TN (North)' || c.BD_Location__c == 'TN (South)'){
                         BOcontestAcceptTnNorthCount = BOcontestAcceptTnNorthCount + 1;
                   }else if(c.BD_Location__c == 'Mum + Goa' || c.BD_Location__c == 'ROM'){
                         BOcontestAcceptMumGoaCount = BOcontestAcceptMumGoaCount + 1;
                   }else {
                         BOcontestAcceptBlankCount = BOcontestAcceptBlankCount + 1;
                   }
                }
            }
            RefundTypeWrapper  BOcontestAcceptListWrapper = New RefundTypeWrapper('Instant resolution - BO contest Accepted', BOcontestAcceptAPcount, BOcontestAcceptdelhiupCount, BOcontestAcceptEastAssamCount, BOcontestAcceptGujaratCount, BOcontestAcceptKNKLCount, BOcontestAcceptdelhiMPCount, BOcontestAcceptTnNorthCount, BOcontestAcceptMumGoaCount, BOcontestAcceptBlankCount, BOcontestAcceptTotalCount,((Decimal.valueOf( BOcontestAcceptTotalCount)/Decimal.valueOf(TotalCount))*100).setScale(0));
            finalMapList.add( BOcontestAcceptListWrapper);
            
           //Instant resolution - BO contest
        List<case>   BOcontestList = Database.query(strQuery +' AND Refund_Type__c=\'Instant resolution - BO contest\'');
            BOcontestAPcount=0; BOcontestdelhiupCount=0;BOcontestdelhiMPCount=0;BOcontestdelhiPunjbCount=0; BOcontestEastAssamCount=0; BOcontestEastWBCount=0; BOcontestGujaratCount=0; BOcontestKNKLCount=0; BOcontestTnNorthCount=0; BOcontestTnSouthCount=0; BOcontestRajasthanCount=0; BOcontestMumGoaCount=0; BOcontestROMCount=0; BOcontestBlankCount=0; BOcontestTotalCount=0;
            if(! BOcontestList.isEmpty()){
                 BOcontestTotalCount = Integer.valueOf( BOcontestList.size());
                for(case c :  BOcontestList){
                     if(c.BD_Location__c == 'Andhra Pradesh' || c.BD_Location__c =='Telangana'){
                         BOcontestAPcount = BOcontestAPcount + 1;
                   }else if(c.BD_Location__c == 'Delhi + UP' || c.BD_Location__c == 'Delhi+Punjab'){
                         BOcontestdelhiupCount = BOcontestdelhiupCount + 1;
                   }else if(c.BD_Location__c == 'East (Assam)' || c.BD_Location__c == 'East (WB)'){
                         BOcontestEastAssamCount = BOcontestEastAssamCount + 1;
                   }else if(c.BD_Location__c == 'Gujarat' || c.BD_Location__c == 'Rajasthan'){
                         BOcontestGujaratCount = BOcontestGujaratCount + 1;
                   }else if(c.BD_Location__c == 'KN + KL' || c.BD_Location__c=='Banglore'){
                         BOcontestKNKLCount = BOcontestKNKLCount + 1;
                   }else if(c.BD_Location__c == 'Madhya Pradesh'){
                         BOcontestdelhiMPCount = BOcontestdelhiMPCount + 1;
                   }else if(c.BD_Location__c == 'TN (North)' || c.BD_Location__c == 'TN (South)'){
                         BOcontestTnNorthCount = BOcontestTnNorthCount + 1;
                   }else if(c.BD_Location__c == 'Mum + Goa' || c.BD_Location__c == 'ROM'){
                         BOcontestMumGoaCount = BOcontestMumGoaCount + 1;
                   }else {
                         BOcontestBlankCount = BOcontestBlankCount + 1;
                   }
                }
            }
            RefundTypeWrapper  BOcontestListWrapper = New RefundTypeWrapper('Instant resolution - BO contest', BOcontestAPcount, BOcontestdelhiupCount, BOcontestEastAssamCount, BOcontestGujaratCount, BOcontestKNKLCount, BOcontestdelhiMPCount, BOcontestTnNorthCount, BOcontestMumGoaCount, BOcontestBlankCount, BOcontestTotalCount,((Decimal.valueOf( BOcontestTotalCount)/Decimal.valueOf(TotalCount))*100).setScale(0));
            finalMapList.add( BOcontestListWrapper);
            
            
        }

            TotalAPcount=InstClsdAplgyAPcount+InstRefundAPcount+InstBOAcceptAPcount+BOcontstRejectAPcount+redBusDelghtAPcount+OutliercaseAPcount+BOcontestAcceptAPcount+BOcontestAPcount;
            
            TotaldelhiupCount=InstClsdAplgydelhiupCount+InstRefunddelhiupCount+InstBOAcceptdelhiupCount+BOcontstRejectdelhiupCount+redBusDelghtdelhiupCount+OutliercasedelhiupCount+BOcontestAcceptdelhiupCount+BOcontestdelhiupCount;
            
            
            TotaldelhiMPCount=InstClsdAplgydelhiMPCount+InstRefunddelhiMPCount+InstBOAcceptdelhiMPCount+BOcontstRejectdelhiMPCount+redBusDelghtdelhiMPCount+OutliercasedelhiMPCount+BOcontestAcceptdelhiMPCount+BOcontestdelhiMPCount;
            
            TotalEastAssamCount=InstClsdAplgyEastAssamCount+InstRefundEastAssamCount+InstBOAcceptEastAssamCount+BOcontstRejectEastAssamCount+redBusDelghtEastAssamCount+OutliercaseEastAssamCount+BOcontestAcceptEastAssamCount+BOcontestEastAssamCount;
            

            TotalGujaratCount=InstClsdAplgyGujaratCount+InstRefundGujaratCount+InstBOAcceptGujaratCount+BOcontstRejectGujaratCount+redBusDelghtGujaratCount+OutliercaseGujaratCount+BOcontestAcceptGujaratCount+BOcontestGujaratCount;
            
            TotalKNKLCount=InstClsdAplgyKNKLCount+InstRefundKNKLCount+InstBOAcceptKNKLCount+BOcontstRejectKNKLCount+redBusDelghtKNKLCount+OutliercaseKNKLCount+BOcontestAcceptKNKLCount+BOcontestKNKLCount;
            
            TotalTnNorthCount=InstClsdAplgyTnNorthCount+InstRefundTnNorthCount+InstBOAcceptTnNorthCount+BOcontstRejectTnNorthCount+redBusDelghtTnNorthCount+OutliercaseTnNorthCount+BOcontestAcceptTnNorthCount+BOcontestTnNorthCount;
            
         
            TotalMumGoaCount=InstClsdAplgyMumGoaCount+InstRefundMumGoaCount+InstBOAcceptMumGoaCount+BOcontstRejectMumGoaCount+redBusDelghtMumGoaCount+OutliercaseMumGoaCount+BOcontestAcceptMumGoaCount+BOcontestMumGoaCount;
            
            TotalBlankCount=InstClsdAplgyBlankCount+InstRefundBlankCount+InstBOAcceptBlankCount+BOcontstRejectBlankCount+redBusDelghtBlankCount+OutliercaseBlankCount+BOcontestAcceptBlankCount+BOcontestBlankCount;
            
        system.debug('Final Map List'+finalMapList);

        return finalMapList;
    }
  
  
  
  public list<StatuspeWrapper> getStatusGroup(){
        List<StatuspeWrapper> finalMapList = New List<StatuspeWrapper>();
        string strQuery = System.Label.BoltOpenCasesQuery;
        List<case> TotalCaseList  = Database.query(strQuery);
        statusTotalCount =0;
        if(!TotalCaseList.isEmpty()){
            statusTotalCount = Integer.valueOf(TotalCaseList.size());
              //Open status
                List<case> openList = Database.query(strQuery +' AND status=\'Open\'');

                openAPcount=0;opendelhiupCount=0;openEastAssamCount=0;openGujaratCount=0;openKNKLCount=0;openTnNorthCount=0;openMumGoaCount=0;opendelhiMPCount=0; openBlankCount=0;openStatusTotalCount=0;
              if(!openList.isEmpty()){
                 openStatusTotalCount = Integer.valueOf(openList.size());
                for(case c : openList){
                     if(c.BD_Location__c == 'Andhra Pradesh' || c.BD_Location__c =='Telangana'){
                        openAPcount =openAPcount + 1;
                   }else if(c.BD_Location__c == 'Delhi + UP' || c.BD_Location__c == 'Delhi+Punjab'){
                        opendelhiupCount =opendelhiupCount + 1;
                   }else if(c.BD_Location__c == 'East (Assam)' || c.BD_Location__c == 'East (WB)'){
                        openEastAssamCount =openEastAssamCount + 1;
                   }else if(c.BD_Location__c == 'Gujarat'|| c.BD_Location__c == 'Rajasthan'){
                        openGujaratCount =openGujaratCount + 1;
                   }else if(c.BD_Location__c == 'KN + KL' || c.BD_Location__c=='Banglore'){
                        openKNKLCount =openKNKLCount + 1;
                   }else if(c.BD_Location__c == 'TN (North)'|| c.BD_Location__c == 'TN (South)' || c.BD_Location__c == 'Tamil Nadu'){
                        openTnNorthCount =openTnNorthCount + 1;
                   }else if(c.BD_Location__c == 'Mum + Goa' || c.BD_Location__c == 'ROM'){
                        openMumGoaCount =openMumGoaCount + 1;
                   }else if(c.BD_Location__c == 'Madhya Pradesh'){
                        opendelhiMPCount =opendelhiMPCount + 1;
                   }else {
                        openBlankCount =openBlankCount + 1;
                   }
                }
            }
            StatuspeWrapper  openstatusWrapper = New StatuspeWrapper('Open',openAPcount,opendelhiupCount,openEastAssamCount,openGujaratCount,openKNKLCount,openTnNorthCount,openMumGoaCount,opendelhiMPCount,openBlankCount,openStatusTotalCount,((Decimal.valueOf(openStatusTotalCount)/Decimal.valueOf(statusTotalCount))*100).setScale(0));
            finalMapList.add(openstatusWrapper);
            
            //Escalated to BD
            List<case> escBDList = Database.query(strQuery +' AND status=\'Escalated to BD\'');
           EsclToBdAPcount=0;EsclToBddelhiupCount=0;EsclToBdEastAssamCount=0;EsclToBdGujaratCount=0;EsclToBdKNKLCount=0;EsclToBdMPCount=0;EsclToBdTnNorthCount=0;EsclToBdMumGoaCount=0; EsclToBdBlankCount=0;EsclToBdTotalCount=0;  
           
            if(!escBDList.isEmpty()){
                EsclToBdTotalCount = Integer.valueOf(escBDList.size());
                for(case c : escBDList){
                     if(c.BD_Location__c == 'Andhra Pradesh' || c.BD_Location__c =='Telangana'){
                        EsclToBdAPcount =EsclToBdAPcount + 1;
                   }else if(c.BD_Location__c == 'Delhi + UP' || c.BD_Location__c == 'Delhi+Punjab'){
                        EsclToBddelhiupCount =EsclToBddelhiupCount + 1;
                   }else if(c.BD_Location__c == 'East (Assam)' || c.BD_Location__c == 'East (WB)'){
                        EsclToBdEastAssamCount =EsclToBdEastAssamCount + 1;
                   }else if(c.BD_Location__c == 'Gujarat' || c.BD_Location__c == 'Rajasthan'){
                        EsclToBdGujaratCount =EsclToBdGujaratCount + 1;
                   }else if(c.BD_Location__c == 'KN + KL' || c.BD_Location__c=='Banglore'){
                        EsclToBdKNKLCount =EsclToBdKNKLCount + 1;
                   }else if(c.BD_Location__c == 'Madhya Pradesh'){
                        EsclToBdMPCount =EsclToBdMPCount + 1;
                   }else if(c.BD_Location__c == 'TN (North)' || c.BD_Location__c == 'TN (South)'){
                        EsclToBdTnNorthCount =EsclToBdTnNorthCount + 1;
                   }else if(c.BD_Location__c == 'Mum + Goa' || c.BD_Location__c == 'ROM'){
                        EsclToBdMumGoaCount =EsclToBdMumGoaCount + 1;
                   }else {
                        EsclToBdBlankCount =EsclToBdBlankCount + 1;
                   }
                }
            }
            StatuspeWrapper escBDListWrapper = New StatuspeWrapper('Escalated to BD',EsclToBdAPcount,EsclToBddelhiupCount,EsclToBdEastAssamCount,EsclToBdGujaratCount,EsclToBdKNKLCount,EsclToBdMPCount,EsclToBdTnNorthCount,EsclToBdMumGoaCount,EsclToBdBlankCount,EsclToBdTotalCount,((Decimal.valueOf(EsclToBdTotalCount)/Decimal.valueOf(statusTotalCount))*100).setScale(0));
            finalMapList.add(escBDListWrapper);
            
             //Re-Open 
            List<case> reopentList = Database.query(strQuery +' AND status=\'Re-Open\'');           
           reopenAPcount=0;reopendelhiupCount=0;reopenEastAssamCount=0;reopenGujaratCount=0;reopenKNKLCount=0;reopenMPCount=0;reopenTnNorthCount=0;reopenMumGoaCount=0; reopenBlankCount=0;reopenTotalCount=0;  
            
            if(!reopentList.isEmpty()){
                reopenTotalCount = Integer.valueOf(reopentList.size());
                for(case c : reopentList){
                     if(c.BD_Location__c == 'Andhra Pradesh' || c.BD_Location__c =='Telangana'){
                        reopenAPcount =reopenAPcount + 1;
                   }else if(c.BD_Location__c == 'Delhi + UP' || c.BD_Location__c == 'Delhi+Punjab'){
                       reopendelhiupCount =reopendelhiupCount + 1;
                   }else if(c.BD_Location__c == 'East (Assam)' || c.BD_Location__c == 'East (WB)'){
                        reopenEastAssamCount =reopenEastAssamCount + 1;
                   }else if(c.BD_Location__c == 'Gujarat' || c.BD_Location__c == 'Rajasthan'){
                        reopenGujaratCount =reopenGujaratCount + 1;
                   }else if(c.BD_Location__c == 'KN + KL' || c.BD_Location__c=='Banglore'){
                        reopenKNKLCount =reopenKNKLCount + 1;
                   }else if(c.BD_Location__c == 'Madhya Pradesh'){
                        reopenMPCount =reopenMPCount + 1;
                   }else if(c.BD_Location__c == 'TN (North)' || c.BD_Location__c == 'TN (South)'){
                       reopenTnNorthCount =reopenTnNorthCount + 1;
                   }else if(c.BD_Location__c == 'Mum + Goa' || c.BD_Location__c == 'ROM'){
                        reopenMumGoaCount =reopenMumGoaCount + 1;
                   }else {
                        reopenBlankCount =reopenBlankCount + 1;
                   }
                }
            }
            StatuspeWrapper reopenWrapper = New StatuspeWrapper('Re-Open',reopenAPcount,reopendelhiupCount,reopenEastAssamCount,reopenGujaratCount,reopenKNKLCount,reopenMPCount,reopenTnNorthCount,reopenMumGoaCount,reopenBlankCount,reopenTotalCount,((Decimal.valueOf(reopenTotalCount)/Decimal.valueOf(statusTotalCount))*100).setScale(0));
            finalMapList.add(reopenWrapper);
            
          //BO Replied   BoReplied
            List<case> borepliedList = Database.query(strQuery +' AND status=\'BO Replied\'');
             
             BoRepliedAPcount=0; BoReplieddelhiupCount=0; BoRepliedEastAssamCount=0;BoRepliedGujaratCount=0;BoRepliedKNKLCount=0;BoRepliedMPCount=0;BoRepliedTnNorthCount=0;BoRepliedMumGoaCount=0;BoRepliedBlankCount=0;BoRepliedTotalCount=0;
             
            if(!borepliedList.isEmpty()){
                BoRepliedTotalCount = Integer.valueOf(borepliedList.size());
                for(case c : borepliedList){
                     if(c.BD_Location__c == 'Andhra Pradesh' || c.BD_Location__c =='Telangana'){
                        BoRepliedAPcount =BoRepliedAPcount + 1;
                   }else if(c.BD_Location__c == 'Delhi + UP' || c.BD_Location__c == 'Delhi+Punjab'){
                        BoReplieddelhiupCount =BoReplieddelhiupCount + 1;
                   }else if(c.BD_Location__c == 'East (Assam)' || c.BD_Location__c == 'East (WB)'){
                        BoRepliedEastAssamCount =BoRepliedEastAssamCount + 1;
                   }else if(c.BD_Location__c == 'Gujarat' || c.BD_Location__c == 'Rajasthan'){
                        BoRepliedGujaratCount =BoRepliedGujaratCount + 1;
                   }else if(c.BD_Location__c == 'KN + KL' || c.BD_Location__c=='Banglore'){
                       BoRepliedKNKLCount =BoRepliedKNKLCount + 1;
                   }else if(c.BD_Location__c == 'Madhya Pradesh'){
                        BoRepliedMPCount =BoRepliedMPCount + 1;
                   }else if(c.BD_Location__c == 'TN (North)'|| c.BD_Location__c == 'TN (South)'){
                       BoRepliedTnNorthCount =BoRepliedTnNorthCount + 1;
                   }else if(c.BD_Location__c == 'Mum + Goa' || c.BD_Location__c == 'ROM'){
                        BoRepliedMumGoaCount =BoRepliedMumGoaCount + 1;
                   }else {
                        BoRepliedBlankCount =BoRepliedBlankCount + 1;
                   }
                }
            }
            StatuspeWrapper borepliedtWrapper = New StatuspeWrapper('BO Replied',BoRepliedAPcount,BoReplieddelhiupCount,BoRepliedEastAssamCount,BoRepliedGujaratCount,BoRepliedKNKLCount,BoRepliedTnNorthCount,BoRepliedMPCount,BoRepliedMumGoaCount,BoRepliedBlankCount,BoRepliedTotalCount,((Decimal.valueOf(BoRepliedTotalCount)/Decimal.valueOf(statusTotalCount))*100).setScale(0));
            finalMapList.add(borepliedtWrapper);
            
            //Department Revert DepRevert
            List<case> deprmntRevertList = Database.query(strQuery +' AND status=\'Department Revert\'');
         DepRevertAPcount=0;DepRevertdelhiupCount=0;DepRevertEastAssamCount=0;DepRevertGujaratCount=0;DepRevertKNKLCount=0;DepRevertMPCount=0;DepRevertTnNorthCount=0; DepRevertMumGoaCount=0;DepRevertBlankCount=0; DepRevertTotalCount=0;
            if(!deprmntRevertList.isEmpty()){
                DepRevertTotalCount = Integer.valueOf(deprmntRevertList.size());
                for(case c : deprmntRevertList){
                     if(c.BD_Location__c == 'Andhra Pradesh'|| c.BD_Location__c =='Telangana'){
                        DepRevertAPcount =DepRevertAPcount + 1;
                   }else if(c.BD_Location__c == 'Delhi + UP' || c.BD_Location__c == 'Delhi+Punjab'){
                        DepRevertdelhiupCount =DepRevertdelhiupCount + 1;
                   }else if(c.BD_Location__c == 'East (Assam)' || c.BD_Location__c == 'East (WB)'){
                        DepRevertEastAssamCount =DepRevertEastAssamCount + 1;
                   }else if(c.BD_Location__c == 'Gujarat' || c.BD_Location__c == 'Rajasthan'){
                        DepRevertGujaratCount =DepRevertGujaratCount + 1;
                   }else if(c.BD_Location__c == 'KN + KL' || c.BD_Location__c=='Banglore'){
                        DepRevertKNKLCount =DepRevertKNKLCount + 1;
                   }else if(c.BD_Location__c == 'Madhya Pradesh'){
                        DepRevertMPCount =DepRevertMPCount + 1;
                   }else if(c.BD_Location__c == 'TN (North)' || c.BD_Location__c == 'TN (South)'){
                        DepRevertTnNorthCount =DepRevertTnNorthCount + 1;
                   }else if(c.BD_Location__c == 'Mum + Goa' || c.BD_Location__c == 'ROM'){
                        DepRevertMumGoaCount =DepRevertMumGoaCount + 1;
                   }else {
                        DepRevertBlankCount =DepRevertBlankCount + 1;
                   }
                }
            }
            StatuspeWrapper deprmntRevertWrapper = New StatuspeWrapper('Department Revert',DepRevertAPcount,DepRevertdelhiupCount,DepRevertEastAssamCount,DepRevertGujaratCount,DepRevertKNKLCount,DepRevertMPCount,DepRevertTnNorthCount,DepRevertMumGoaCount,DepRevertBlankCount,DepRevertTotalCount,((Decimal.valueOf(DepRevertTotalCount)/Decimal.valueOf(statusTotalCount))*100).setScale(0));
            finalMapList.add(deprmntRevertWrapper);
            
            //Awaiting BO/BD Response   AwatngBoBdResp
            List<case> awtngbobdrespList = Database.query(strQuery +' AND status=\'Awaiting BO/BD Response\'');
            AwatngBoBdRespAPcount=0;AwatngBoBdRespdelhiupCount=0; AwatngBoBdRespEastAssamCount=0;AwatngBoBdRespGujaratCount=0;AwatngBoBdRespKNKLCount=0;AwatngBoBdRespMPCount=0;AwatngBoBdRespTnNorthCount=0;AwatngBoBdRespMumGoaCount=0;AwatngBoBdRespBlankCount=0;AwatngBoBdRespTotalCount=0;
            if(! awtngbobdrespList.isEmpty()){
                 AwatngBoBdRespTotalCount = Integer.valueOf( awtngbobdrespList.size());
                for(case c :  awtngbobdrespList){
                     if(c.BD_Location__c == 'Andhra Pradesh' || c.BD_Location__c =='Telangana'){
                         AwatngBoBdRespAPcount = AwatngBoBdRespAPcount + 1;
                   }else if(c.BD_Location__c == 'Delhi + UP' || c.BD_Location__c == 'Delhi+Punjab'){
                         AwatngBoBdRespdelhiupCount = AwatngBoBdRespdelhiupCount + 1;
                   }else if(c.BD_Location__c == 'East (Assam)' || c.BD_Location__c == 'East (WB)'){
                         AwatngBoBdRespEastAssamCount = AwatngBoBdRespEastAssamCount + 1;
                   }else if(c.BD_Location__c == 'Gujarat' || c.BD_Location__c == 'Rajasthan'){
                         AwatngBoBdRespGujaratCount = AwatngBoBdRespGujaratCount + 1;
                   }else if(c.BD_Location__c == 'KN + KL' || c.BD_Location__c=='Banglore'){
                         AwatngBoBdRespKNKLCount = AwatngBoBdRespKNKLCount + 1;
                   }else if(c.BD_Location__c == 'Madhya Pradesh'){
                         AwatngBoBdRespMPCount = AwatngBoBdRespMPCount + 1;
                   }else if(c.BD_Location__c == 'TN (North)' || c.BD_Location__c == 'TN (South)'){
                         AwatngBoBdRespTnNorthCount = AwatngBoBdRespTnNorthCount + 1;
                   }else if(c.BD_Location__c == 'Mum + Goa' || c.BD_Location__c == 'ROM'){
                         AwatngBoBdRespMumGoaCount = AwatngBoBdRespMumGoaCount + 1;
                   }else {
                         AwatngBoBdRespBlankCount = AwatngBoBdRespBlankCount + 1;
                   }
                }
            }
            StatuspeWrapper  awtngbobdrespWrapper = New StatuspeWrapper('Awaiting BO/BD Response', AwatngBoBdRespAPcount, AwatngBoBdRespdelhiupCount, AwatngBoBdRespEastAssamCount, AwatngBoBdRespGujaratCount, AwatngBoBdRespKNKLCount, AwatngBoBdRespMPCount, AwatngBoBdRespTnNorthCount, AwatngBoBdRespMumGoaCount, AwatngBoBdRespBlankCount, AwatngBoBdRespTotalCount,((Decimal.valueOf(AwatngBoBdRespTotalCount)/Decimal.valueOf(statusTotalCount))*100).setScale(0));
            finalMapList.add(awtngbobdrespWrapper);
            
             // Waiting for Customer    WatngforCustmr
            List<case> wtngfrcustrList = Database.query(strQuery +' AND status=\'Waiting for Customer\'');
          WatngforCustmrAPcount=0; WatngforCustmrdelhiupCount=0;WatngforCustmrEastAssamCount=0;WatngforCustmrGujaratCount=0;WatngforCustmrKNKLCount=0;WatngforCustmrMPCount=0; WatngforCustmrTnNorthCount=0; WatngforCustmrMumGoaCount=0;WatngforCustmrBlankCount=0;WatngforCustmrTotalCount=0;
            if(! wtngfrcustrList.isEmpty()){
               WatngforCustmrTotalCount = Integer.valueOf( wtngfrcustrList.size());
                for(case c :  wtngfrcustrList){
                     if(c.BD_Location__c == 'Andhra Pradesh' || c.BD_Location__c =='Telangana'){
                       WatngforCustmrAPcount = WatngforCustmrAPcount + 1;
                   }else if(c.BD_Location__c == 'Delhi + UP' || c.BD_Location__c == 'Delhi+Punjab'){
                       WatngforCustmrdelhiupCount = WatngforCustmrdelhiupCount + 1;
                   }else if(c.BD_Location__c == 'East (Assam)' || c.BD_Location__c == 'East (WB)'){
                       WatngforCustmrEastAssamCount = WatngforCustmrEastAssamCount + 1;
                   }else if(c.BD_Location__c == 'Gujarat' || c.BD_Location__c == 'Rajasthan'){
                       WatngforCustmrGujaratCount = WatngforCustmrGujaratCount + 1;
                   }else if(c.BD_Location__c == 'KN + KL' || c.BD_Location__c=='Banglore'){
                       WatngforCustmrKNKLCount = WatngforCustmrKNKLCount + 1;
                   }else if(c.BD_Location__c == 'Madhya Pradesh'){
                       WatngforCustmrMPCount = WatngforCustmrMPCount + 1;
                   }else if(c.BD_Location__c == 'TN (North)' || c.BD_Location__c == 'TN (South)'){
                       WatngforCustmrTnNorthCount = WatngforCustmrTnNorthCount + 1;
                   }else if(c.BD_Location__c == 'Mum + Goa' || c.BD_Location__c == 'ROM'){
                       WatngforCustmrMumGoaCount = WatngforCustmrMumGoaCount + 1;
                   }else {
                       WatngforCustmrBlankCount = WatngforCustmrBlankCount + 1;
                   }
                }
            }
            StatuspeWrapper  wtngfrcustrListWrapper = New StatuspeWrapper('Waiting for Customer', WatngforCustmrAPcount, WatngforCustmrdelhiupCount, WatngforCustmrEastAssamCount, WatngforCustmrGujaratCount, WatngforCustmrKNKLCount, WatngforCustmrMPCount, WatngforCustmrTnNorthCount, WatngforCustmrMumGoaCount, WatngforCustmrBlankCount, WatngforCustmrTotalCount,((Decimal.valueOf(WatngforCustmrTotalCount)/Decimal.valueOf(statusTotalCount))*100).setScale(0));
            finalMapList.add(wtngfrcustrListWrapper);          
                
        }
        
            TotalAPcount=openAPcount+EsclToBdAPcount+reopenAPcount+BoRepliedAPcount+DepRevertAPcount+AwatngBoBdRespAPcount+WatngforCustmrAPcount;
            
            TotaldelhiupCount=opendelhiupCount+EsclToBddelhiupCount+reopendelhiupCount+BoReplieddelhiupCount+DepRevertdelhiupCount+AwatngBoBdRespdelhiupCount+WatngforCustmrdelhiupCount;
            
            TotalEastAssamCount=openEastAssamCount+EsclToBdEastAssamCount+reopenEastAssamCount+BoRepliedEastAssamCount+DepRevertEastAssamCount+AwatngBoBdRespEastAssamCount+WatngforCustmrEastAssamCount;
            
            TotalGujaratCount=openGujaratCount+EsclToBdGujaratCount+reopenGujaratCount+BoRepliedGujaratCount+DepRevertGujaratCount+AwatngBoBdRespGujaratCount+WatngforCustmrGujaratCount;
            
            TotalKNKLCount=openKNKLCount+EsclToBdKNKLCount+reopenKNKLCount+BoRepliedKNKLCount+DepRevertKNKLCount+AwatngBoBdRespKNKLCount+WatngforCustmrKNKLCount;
            
            TotaldelhiMPCount=opendelhiMPCount+EsclToBdMPCount+reopenMPCount+BoRepliedMPCount+DepRevertMPCount+AwatngBoBdRespMPCount+WatngforCustmrMPCount;
            
            TotalTnNorthCount=openTnNorthCount+EsclToBdTnNorthCount+reopenTnNorthCount+BoRepliedTnNorthCount+DepRevertTnNorthCount+AwatngBoBdRespTnNorthCount+WatngforCustmrTnNorthCount;
            
            TotalMumGoaCount=openMumGoaCount+EsclToBdMumGoaCount+reopenMumGoaCount+BoRepliedMumGoaCount+DepRevertMumGoaCount+AwatngBoBdRespMumGoaCount+WatngforCustmrMumGoaCount;
            
            TotalBlankCount=openBlankCount+EsclToBdBlankCount+reopenBlankCount+BoRepliedBlankCount+DepRevertBlankCount+AwatngBoBdRespBlankCount+WatngforCustmrBlankCount;
            
        system.debug('Final Map List'+finalMapList);

        return finalMapList;
    }
  
  




    public class RefundTypeWrapper{
    public string status {get; set;}
    public Integer apCount{get;set;}
    public Integer delhiupCount{get;set;}
    public Integer EastAssamCount{get;set;}
    public Integer GujaratCount{get;set;}
    public Integer KNKLCount{get;set;}
    public Integer delhiMPCount{get;set;}
    public Integer TnNorthCount{get;set;}
    public Integer MumGoaCount{get;set;}
    public Integer BlankCount{get;set;}
    public Integer totalContributon {get; set;}
    public Decimal percentageContributon {get;set;}
        

        public RefundTypeWrapper(String reundType, Integer apCount, Integer delhiupCount,Integer EastAssamCount,Integer GujaratCount,Integer KNKLCount,Integer delhiMPCount,Integer TnNorthCount,Integer MumGoaCount,Integer BlankCount,Integer total, decimal percent){
            this.status = reundType;
            this.apCount = apCount;
            this.delhiupCount = delhiupCount;
            this.EastAssamCount = EastAssamCount;
            this.GujaratCount = GujaratCount;
            this.KNKLCount = KNKLCount;
            this.delhiMPCount = delhiMPCount;
            this.TnNorthCount = TnNorthCount;
            this.MumGoaCount = MumGoaCount;
            this.BlankCount = BlankCount;
            this.totalContributon = total;
            this.percentageContributon = percent;
        }
    }
    
    public class StatuspeWrapper{
    public string status {get; set;}
    public Integer apCounts{get;set;}
    public Integer delhiupCounts{get;set;}
    public Integer EastAssamCounts{get;set;}
    public Integer GujaratCounts{get;set;}
    public Integer KNKLCounts{get;set;}
    public Integer delhiMPCounts{get;set;}
    public Integer TnNorthCounts{get;set;}
    public Integer MumGoaCounts{get;set;}
    public Integer BlankCounts{get;set;}
    public Integer totalContributon {get; set;}
    public Decimal percentageContributon {get;set;}
        

        public StatuspeWrapper(String pg, Integer apCount, Integer delhiupCount,Integer EastAssamCount,Integer GujaratCount,Integer KNKLCount,Integer delhiMPCount,Integer TnNorthCount,Integer MumGoaCount,Integer BlankCount,Integer total, decimal percent){

            this.status = pg;
            this.apCounts = apCount;
            this.delhiupCounts = delhiupCount;
            this.EastAssamCounts = EastAssamCount;
            this.GujaratCounts = GujaratCount;
            this.KNKLCounts = KNKLCount;
            this.delhiMPCounts = delhiMPCount;
            this.TnNorthCounts = TnNorthCount;
            this.MumGoaCounts = MumGoaCount;
            this.BlankCounts = BlankCount;
            this.totalContributon = total;
            this.percentageContributon = percent;
         }
       } 
}