/*
* Name           : CallBackRecordsControllerTest
* Created Date   : 13 May 2019
* Created By     : Sreenivas M
* Purpose        : Test Class for CallBackRecordsController
*/
@isTest
public class CallBackRecordsControllerTest
{
    static testMethod void callBackStatus()
    {
    
        Test.startTest();
        CallBackRecordsController cbRec = new CallBackRecordsController();
       
        Test.stopTest();
       } 
    }